ffmpeg -i "A#2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-As2.mp3
ffmpeg -i "A#3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-As3.mp3
ffmpeg -i "A#4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-As4.mp3
ffmpeg -i "A#5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-As5.mp3
ffmpeg -i "A2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-A2.mp3
ffmpeg -i "A3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-A3.mp3
ffmpeg -i "A4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-A4.mp3
ffmpeg -i "A5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-A5.mp3
ffmpeg -i "B2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-B2.mp3
ffmpeg -i "B3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-B3.mp3
ffmpeg -i "B4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-B4.mp3
ffmpeg -i "B5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-B5.mp3
ffmpeg -i "C#3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Cs3.mp3
ffmpeg -i "C#4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Cs4.mp3
ffmpeg -i "C#5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Cs5.mp3
ffmpeg -i "C3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-C3.mp3
ffmpeg -i "C4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-C4.mp3
ffmpeg -i "C5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-C5.mp3
ffmpeg -i "D#3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Ds3.mp3
ffmpeg -i "D#4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Ds4.mp3
ffmpeg -i "D#5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Ds5.mp3
ffmpeg -i "D3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-D3.mp3
ffmpeg -i "D4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-D4.mp3
ffmpeg -i "D5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-D5.mp3
ffmpeg -i "E2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-E2.mp3
ffmpeg -i "E3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-E3.mp3
ffmpeg -i "E4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-E4.mp3
ffmpeg -i "E5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-E5.mp3
ffmpeg -i "F#2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Fs2.mp3
ffmpeg -i "F#3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Fs3.mp3
ffmpeg -i "F#4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Fs4.mp3
ffmpeg -i "F#5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Fs5.mp3
ffmpeg -i "F2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-F2.mp3
ffmpeg -i "F3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-F3.mp3
ffmpeg -i "F4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-F4.mp3
ffmpeg -i "F5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-F5.mp3
ffmpeg -i "G#2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Gs2.mp3
ffmpeg -i "G#3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Gs3.mp3
ffmpeg -i "G#4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Gs4.mp3
ffmpeg -i "G#5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-Gs5.mp3
ffmpeg -i "G2.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-G2.mp3
ffmpeg -i "G3.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-G3.mp3
ffmpeg -i "G4.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-G4.mp3
ffmpeg -i "G5.wav" -acodec libmp3lame -q:a 0 -map 0:a:0 electric-guitar-G5.mp3